export const positionNavHeaders = {
    "start/": "APM-CRT Task",
    "start/details": "Experiment Details",
    "start/consent": "Consent Form",
    "start/guidelines": "General Guidelines",
    "demographic/instructions": "About You",
    "demographic/task": "About You",
    "task/introduction": "Task 1",
    "task/example": "Task 1",
    "task/demo": "Task 1",
    "task/puzzle": "Task 1",
    "task/conclusion": "Task 1",
    "crt/instructions": "Task 2",
    "crt/example1": "Task 2",
    "crt/demo": "Task 2",
    "crt/task1": "Task 2",
    "crt/task2": "Task 2",
    "crt/conclusion": "Task 2",
    "feedback/instructions": "Feedback",
    "feedback/task": "Feedback"
}